services:
  - type: web
    name: focus-tracker-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn model.app:app
    envVars:
      - key: GOOGLE_API_KEY
        value: AIzaSyAVxpchnJRs6c75QBTgPA_Wj3Zx5GmXbpI
